[profile.default]
# solc_version = "0.8.23"
# evm_version = "shanghai"
solc_version = "0.8.30"
evm_version = "prague"

ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]

via_ir = true
# TODO create a release profile with optimizer true and time 9,999,999
# optimizer = true

libs = ["lib"]
out = "out"
src = "src"
env = ".env"

remappings = [
    "@forge-std/=lib/forge-std/src/",
    "@jincubator/limit-order-protocol/=lib/limit-order-protocol/",
    "@1inch/solidity-utils/=lib/solidity-utils/",
    "@jincubator/the-compact/=lib/the-compact/",
    "@jincubator/tycho-execution/=lib/tycho-execution/",
    "@openzeppelin/=lib/tycho-execution/foundry/lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/",
    "@permit2/=lib/tycho-execution/foundry/lib/permit2/",
    "@uniswap-v2/=lib/tycho-execution/foundry/lib/v2-core/",
    "@uniswap/v3-core/=lib/tycho-execution/foundry/lib/v3-core/",
    "@uniswap/v4-core/=lib/tycho-execution/foundry/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/tycho-execution/foundry/lib/v4-periphery/",
    "@interfaces/=lib/tycho-execution/foundry/interfaces/",
    "@src/=lib/tycho-execution/foundry/src/",
    "@ekubo/=lib/tycho-execution/foundry/lib/ekubo/",
    "@solady/=lib/tycho-execution/foundry/lib/solady/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
